//Version 1
CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_PROFILE(
    OID VARCHAR(32) NOT NULL,
    VERSION INTEGER NOT NULL,
    CREATE_ACCOUNT VARCHAR(50),
    CREATE_DATE TIMESTAMP,
    UPDATE_ACCOUNT VARCHAR(50),
    UPDATE_DATE TIMESTAMP,
    ADDRESS VARCHAR(50),
    ADMIN CHAR(1)
);
ALTER TABLE PUBLIC.T_PROFILE ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_4 PRIMARY KEY(OID);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_USER(
    OID VARCHAR(32) NOT NULL,
    VERSION INTEGER NOT NULL,
    CREATE_ACCOUNT VARCHAR(50),
    CREATE_DATE TIMESTAMP,
    UPDATE_ACCOUNT VARCHAR(50),
    UPDATE_DATE TIMESTAMP,
    NAME VARCHAR(50),
    GENDER VARCHAR(10),
    PROFILE_ID VARCHAR(32)
);
ALTER TABLE PUBLIC.T_USER ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_94 PRIMARY KEY(OID);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_ROLE(
    OID VARCHAR(32) NOT NULL,
    CREATE_ACCOUNT VARCHAR(50),
    CREATE_DATE TIMESTAMP,
    UPDATE_ACCOUNT VARCHAR(50),
    UPDATE_DATE TIMESTAMP,
    VERSION INTEGER,
    NAME VARCHAR(50)
);
ALTER TABLE PUBLIC.T_ROLE ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_9 PRIMARY KEY(OID);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.T_USER_ROLE_MAPPING(
    USER_OID VARCHAR(32) NOT NULL,
    ROLE_OID VARCHAR(32) NOT NULL
);

ALTER TABLE PUBLIC.T_USER_ROLE_MAPPING ADD CONSTRAINT IF NOT EXISTS PUBLIC.FK3B8B32AE8A33C50 FOREIGN KEY(USER_OID) REFERENCES PUBLIC.T_USER(OID) NOCHECK;
ALTER TABLE PUBLIC.T_USER_ROLE_MAPPING ADD CONSTRAINT IF NOT EXISTS PUBLIC.FK3B8B32AE8A01826 FOREIGN KEY(ROLE_OID) REFERENCES PUBLIC.T_ROLE(OID) NOCHECK;
ALTER TABLE PUBLIC.T_USER ADD CONSTRAINT IF NOT EXISTS PUBLIC.FK94B9B0D6F0EB7D8B FOREIGN KEY(PROFILE_ID) REFERENCES PUBLIC.T_PROFILE(OID) NOCHECK;